version: '3'

services:
  backend:
    build:
      context: "./backend"
      target: base
    volumes:
      - type: bind
        source: ./backend
        target: /app/go/base
    ports:
      - 8080:8080
    command: "air -c .air.toml"

  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend/chatapp
        target: /app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
